### ISSUE TITLE
Change default Retina check to 2160x1440

### ISSUE THREAD

**Issue by flipswitchingmonkey** [braitsch/ofxDatGui#116]
Currently you're checking for 2560x1600, however in the case of the Surface Pro for example, which uses a high DPI display, it is just 2160x1440.

It's easy to change in OfxDatGuiTheme.h, but maybe a more lenient default would be good?

**Comment by kritzikratzi** [comment]
you can use my code from ofxMightyUI. 
it detects the pixelDensity (scale factor) instead of assuming retina (2x). 
this is neat esp. with windows where it's not always x2, x4 etc. 

iOS: 
https://github.com/kritzikratzi/ofxMightyUI/blob/e32b358e9473f4a1400422cfddc3ba681f100f97/src/ofxMightyUI.cpp#L26

OSX: 
https://github.com/kritzikratzi/ofxMightyUI/blob/e32b358e9473f4a1400422cfddc3ba681f100f97/src/ofxMightyUI.cpp#L80

Windows: 
https://github.com/kritzikratzi/ofxMightyUI/blob/e32b358e9473f4a1400422cfddc3ba681f100f97/src/ofxMightyUI.cpp#L87

**Comment by braitsch** [comment]
@flipswitchingmonkey What would be a more lenient approach? Constants need to be defined somewhere.

**Comment by flipswitchingmonkey** [comment]
@kritzikratzi 's approach looks promising, though I haven't had time to try it yet.
