### ISSUE TITLE
Delete doesn't work with color picker in a folder

### ISSUE THREAD

**Issue by janrope** [braitsch/ofxDatGui#131]
The destructor of ofxDatGui causes a "Access violation reading location" error if it contains an ofxDatGuiFolder which itself contains an ofxDatGuiColorPicker.

The exception is thrown at  ~ofxDatGuiGroup().

Add the following code for a MWE:

**ofApp.h**

#include "ofMain.h"
#include "ofxDatGui.h"

class ofApp : public ofBaseApp{
	
public:
	void setup();
	void update();
	ofxDatGui* gui;
};

**ofApp.ccp**

#include "ofApp.h"

void ofApp::setup(){
	gui = new ofxDatGui(ofxDatGuiAnchor::TOP_LEFT);
	ofxDatGuiFolder* ofFolder = gui->addFolder("Draw options", ofColor::orangeRed);
	ofFolder->addColorPicker("- Cross color", ofColor::gray);
}

void ofApp::update(){
	delete gui;
}

**Comment by braitsch** [comment]
Calling delete in your update loop calls delete multiple times so essentially you're trying to delete something that doesn't exist after the first time it is deleted, hence the error. Calling delete on say a keypress or mouse click will delete the GUI once instead of trying to delete it over and over again. 
````
void ofApp::keyPressed(int key){
    if (key == 'd') delete gui;
}
````
