### ISSUE TITLE
Indent widgets

### ISSUE THREAD

**Issue by martialgallorini** [braitsch/ofxDatGui#16]
Would be nice to indent (or other visual trick) widgets according to their parenting links (imbrication). It is a bit difficult to identify hierarchy when using lot of widgets.

**Comment by braitsch** [comment]
I played around with indenting labels and even the components themselves to help visually communicate a hierarchy and didn't care for how it looked which is why I introduced padded breaks and folders with common color banding. One possible solution though to help with this might be to allow the components within a group to share a common background color (or template styling) in addition to the banding.

**Comment by martialgallorini** [comment]
A slight indent could help i think.
Or maybe make the unfolded background slightly lighter for example
