### ISSUE TITLE
Custom/Alternative themes override component color settings

### ISSUE THREAD

**Issue by tyhenry** [braitsch/ofxDatGui#91]
Title says it all, but perhaps there's a way of enabling alternative themes that doesn't override custom component colors?

For instance, I have:

```
class GuiTheme : public ofxDatGuiTheme {
public:
    GuiTheme()
    {
        font.size = 8;
        layout.width = 400;
        init();
    }
};
gui* = new ofxDatGui(0,0);
gui->setTheme (new GuiTheme())
ofxDatGuiSlider* slider = gui->addSlider("my slider",1,100);
slider->setStripeColor(ofColor::green);
```

But the slider ends up with a blue stripe.  Any ideas?

Thanks for the addon in any case - it's fantastic overall.

**Comment by braitsch** [comment]
``gui->setTheme()`` is applied, by default, on the next ``gui->update()`` call which allows you to add components **after** applying a theme and have those components absorb the theme's settings. I just added an optional ``applyImmediately`` flag which will force the theme to be applied immediately instead of waiting until the next ``gui->update()`` call. 

In your case the following will give you what you want:

````
gui = new ofxDatGui();
gui->setTheme (new GuiTheme(), true); // <- apply the theme immediately
ofxDatGuiSlider* slider = gui->addSlider("my slider", 1, 100);
slider->setStripeColor(ofColor::green);
````

**Comment by tyhenry** [comment]
Great, thanks for the quick commit! 
That makes sense now about the gui->update() call placement and how the theme and component settings are ordered.
With that info I was able to do:
```
class GuiTheme : public ofxDatGuiTheme {
public:
    GuiTheme()
    {
        font.size = 8;
        layout.width = 400;
        layout.labelWidth = 180;
        init();
    }
};
gui* = new ofxDatGui(0,0);
gui->setTheme (new GuiTheme())
ofxDatGuiSlider* slider = gui->slider("my slider",1,100);
// update manually here to apply theme settings on gui w/ slider
gui->update();
// now change component level settings
slider->setStripeColor(ofColor::green);
```
